sudo: required
dist: xenial
env:
  global:
  - CHANGE_MINIKUBE_NONE_USER=true
  - MINIKUBE_WANTUPDATENOTIFICATION=false
  - MINIKUBE_WANTREPORTERRORPROMPT=false
  - MINIKUBE_HOME=$HOME
  - CHANGE_MINIKUBE_NONE_USER=true
  - KUBECONFIG=$HOME/.kube/config
services:
- docker
language: go
go:
- 1.12.9
addons:
  apt:
    update: true
install:
- make bootstrap
- make format
before_script:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
  && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.4.0/minikube-linux-amd64
  && chmod +x minikube && sudo mv minikube /usr/local/bin/
- mkdir -p $HOME/.kube $HOME/.minikube
- touch $KUBECONFIG
- sudo minikube start --vm-driver=none --kubernetes-version=v1.16.0
- 'sudo chown -R travis: /home/travis/.minikube/'
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
  until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
  sleep 1; done
script:
- kubectl cluster-info
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
  until kubectl -n kube-system get pods -lcomponent=kube-addon-manager -o jsonpath="$JSONPATH"
  2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-addon-manager to
  be available"; kubectl get pods --all-namespaces; done
- kubectl get deployment
- "./buildscripts/travis-build.sh"
- sudo apt-get install -y open-iscsi
- sudo service iscsid start
- "./ci/ci-test.sh"
after_success:
- make deploy-images
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
    - kiran.mova@openebs.io
deploy:
  provider: releases
  api_key:
    secure: JYNHyi2m9pqOitOen9zX6FYjU0Q/uNjUhMpUDvHYq+RlqQ7zliJfiecRe91l+LKW1AmnGhNp4f2Shu2R9dQJwmle6y5ohsts3wRlRLAKxoex6jXo8uxCMVS5wE7+MlMmPWXaBSGy4Hcds+Jpzr90knO1avCDVdsM3ETbaE5tVQJuW8tgiCkWs+3V1xsjtpfT2s61tyikdbrRX1BevyN4/0mm0fJiowq8IelWwe+FEDUsVY3qg9D/aw7yEG9ApL34livin/VkWFqKq9ih1uB3timOjY3tVMyAgpmKcYqPxJPy3GjWYOeutwJcQZj8Zb4BowpVBj7rA70Fgqs9nVQXUyfc6LQ80+QIU+WBswqFGLA+SzyEGo/k+P45gYiawW4m3Bfap58X5hiQpUpHs5QBZuWC6cDt7q+BInf/+wlRI9pJF3QIv7KTEaySNdUtysMoAw0WGl5Sr7FtGrKKdyZB5E/eKbXGraCMXiY+jX2+YtUgyynO+G3gSY5PVr2BTseSFCCXLcvY8PG+x2ecc5nk4nNhpFkWrzGdwZJiriIMxrXStKB8dUWd55LEvuO475nbNUpnYVMY+br4NpUyqPyG33BM4my5sK8BimT6YO1tFsoFPx9TXSpuDAuk3QTzjZZET8P7SlFqJRwSjfLV1UkjrvHMkRaN7nSGmBaxtAP8Ucw=
  file: bin/csi/csi-linux_*.zip
  skip_cleanup: true
  overwrite: true
  on:
    repo: openebs/csi
    tags: true
branches:
  except:
  - "/^*-v[0-9]/"
