sudo: required
dist: xenial
env:
  global:
  - CHANGE_MINIKUBE_NONE_USER=true
  - MINIKUBE_WANTUPDATENOTIFICATION=false
  - MINIKUBE_WANTREPORTERRORPROMPT=false
  - MINIKUBE_HOME=$HOME
  - CHANGE_MINIKUBE_NONE_USER=true
  - KUBECONFIG=$HOME/.kube/config
services:
- docker
language: go
go:
- 1.14.7
addons:
  apt:
    update: true

before_install:
- sudo apt-get -qq -y install conntrack

install:
- make bootstrap
- make format
before_script:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.1/bin/linux/amd64/kubectl
  && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.8.1/minikube-linux-amd64
  && chmod +x minikube && sudo mv minikube /usr/local/bin/
- mkdir -p $HOME/.kube $HOME/.minikube
- touch $KUBECONFIG
- sudo minikube start --profile=minikube --vm-driver=none --kubernetes-version=v1.18.1
- minikube update-context --profile=minikube
- "sudo chown -R travis: /home/travis/.minikube/"
- eval "$(minikube docker-env --profile=minikube)" && export DOCKER_CLI='docker'
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
  until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
  sleep 1; done
script:
- kubectl cluster-info
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
  until kubectl -n kube-system get pods -lk8s-app=kube-dns -o jsonpath="$JSONPATH"
  2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-dns to
  be available"; kubectl get pods --all-namespaces; done
- "./buildscripts/travis-build.sh"
- sudo apt-get install -y open-iscsi
- sudo service iscsid start
- "./ci/ci-test.sh"
after_success:
- make deploy-images
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
    - kiran.mova@mayadata.io
    - prateek.pandey@mayadata.io
