kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: block-claim
spec:
  volumeMode: Block
  storageClassName: cstor-sparse-auto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
