# Ubuntu 18.04 and above
spec:
  containers:
    - name: openebs-csi-plugin
      volumeMounts:
        - name: iscsiadm-bin
          mountPath: /sbin/iscsiadm
        - name: iscsiadm-lib-isns-nocrypto
          mountPath: /lib/x86_64-linux-gnu/libisns-nocrypto.so.0
  volumes:
    - name: iscsiadm-bin
      hostPath:
        path: /sbin/iscsiadm
        type: File
    - name: iscsiadm-lib-isns-nocrypto
      hostPath:
        path: /lib/x86_64-linux-gnu/libisns-nocrypto.so.0
        type: File

# SUSE Linux Enterprise Server 12
spec:
  containers:
    - name: openebs-csi-plugin
      volumeMounts:
        - name: iscsiadm-bin
          mountPath: /sbin/iscsiadm
        - name: iscsiadm-lib-crypto
          mountPath: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
        - name: iscsiadm-lib-openiscsiusr
          mountPath: /lib/x86_64-linux-gnu/libopeniscsiusr.so.0.2.0
  volumes:
    - name: iscsiadm-bin
      hostPath:
        path: /sbin/iscsiadm
        type: File
    - name: iscsiadm-lib-crypto
      hostPath:
        path: /lib64/libcrypto.so.1.0.0
        type: File
    - name: iscsiadm-lib-openiscsiusr
      hostPath:
        path: /usr/lib64/libopeniscsiusr.so.0.2.0
        type: File

# SUSE Linux Enterprise Server 15
spec:
  containers:
    - name: openebs-csi-plugin
      volumeMounts:
        - name: iscsiadm-bin
          mountPath: /sbin/iscsiadm
        - name: iscsiadm-lib-crypto
          mountPath: /lib/x86_64-linux-gnu/libcrypto.so.1.1
        - name: iscsiadm-lib-openiscsiusr
          mountPath: /lib/x86_64-linux-gnu/libopeniscsiusr.so.0.2.0
  volumes:
    - name: iscsiadm-bin
      hostPath:
        path: /sbin/iscsiadm
        type: File
    - name: iscsiadm-lib-crypto
      hostPath:
        path: /usr/lib64/libcrypto.so.1.1
        type: File
    - name: iscsiadm-lib-openiscsiusr
      hostPath:
        path: /usr/lib64/libopeniscsiusr.so.0.2.0
        type: File
