kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-csi-vol-claim-csi
spec:
  storageClassName: openebs-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi

