---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: demo-snapshot
spec:
  volumeSnapshotClassName: cstor-csi-snapclass
  source:
    persistentVolumeClaimName: demo-csivol-claim
---
