# Copyright 2020 The OpenEBS Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ci

on:
  pull_request:
    branches:
      # on pull requests to develop and release branches
      - 'develop'
      - 'v*'
    paths-ignore:
      - '*.md'
      - 'changelogs/**'
      - 'docs/**'
      - 'LICENSE'
      - 'MAINTAINERS'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: '.'
          pattern: '*.sh'

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unit test
        run: make test

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1

  e2e-tests:
    needs: ['unit-test']
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.25.16]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.16.5
        uses: actions/setup-go@v4
        with:
          go-version: 1.16.5

      - name: Setup Minikube-Kubernetes
        uses: medyagh/setup-minikube@latest
        with:
          cache: false
          minikube-version: 1.31.1
          driver: none
          kubernetes-version: ${{ matrix.kubernetes }}
          cni: calico
          start-args: '--install-addons=false'

      - name: Set tag
        run: |
          BRANCH="${GITHUB_REF##*/}"
          CI_TAG=${BRANCH#v}-ci
          if [ ${BRANCH} = "develop" ]; then
            CI_TAG="ci"
          fi
          echo "TAG=${CI_TAG}" >> $GITHUB_ENV
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV

      - name: Build images locally
        run: make csi-driver-image || exit 1;

      - name: Install tests dependencies
        run: make bootstrap

      - name: Running tests
        run: ./ci/ci-test.sh

  csi-driver:
    runs-on: ubuntu-latest
    needs: ['lint', 'unit-test', 'e2e-tests']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.5.1

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./buildscripts/cstor-csi-driver/cstor-csi-driver.Dockerfile
          push: false
          platforms: linux/amd64, linux/arm64
          tags: |
            openebs/cstor-csi-driver:ci